repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict

  - repo: https://github.com/Lucas-C/pre-commit-hooks-lxml
    rev: v1.1.0
    hooks:
      - id: forbid-html-img-without-alt-text
      - id: forbid-non-std-html-attributes
      - id: detect-missing-css-classes
        args:
          - --css-files-dir
          - .
          - --html-files-dir
          - .
  - repo: https://github.com/prettier/prettier
    rev: 2.1.2
    hooks:
      - id: prettier
